on: push

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Install faketime
        run: |
          sudo apt-get update
          sudo apt-get install libfaketime
      - name: Base case command
        id: test_base
        uses: ./
        env:
          LD_PRELOAD: /usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1
          FAKETIME: 2021-12-31 23:59:59
        with:
          token: test_token
          run_group_id: 42
          dry_run: true
      - name: Base case test
        uses: ./.github/actions/test
        with:
          actual: ${{ steps.test_base.outputs.command }}
          expected: run --skip-update --token "test_token" --run-group 42 --junit-file results/rainforest/junit.xml --save-run-id .rainforest_run_id --description "rainforestapp/github-action - ${{ github.ref_name }} test 2021-12-31T23:59:59Z" --release "${{ github.sha }}"
      - name: All parameters command
        id: test_all_parameters
        uses: ./
        with:
          token: test_token
          run_group_id: 42
          description: foo bar
          environment_id: 117
          conflict: cancel-all
          crowd: automation
          release: '1.0'
          background: true
          dry_run: true
      - name: All parameters test
        uses: ./.github/actions/test
        with:
          actual: ${{ steps.test_all_parameters.outputs.command }}
          expected: run --skip-update --token "test_token" --run-group 42 --junit-file results/rainforest/junit.xml --save-run-id .rainforest_run_id --conflict cancel-all --environment-id 117 --crowd automation --description "foo bar" --release "1.0" --background
      - name: Custom URL command
        id: test_custom_url
        uses: ./
        with:
          token: test_token
          run_group_id: 42
          description: foo bar
          custom_url: https://something.com
          release: '1.0'
          dry_run: true
      - name: Custom URL test
        uses: ./.github/actions/test
        with:
          actual: ${{ steps.test_custom_url.outputs.command }}
          expected: run --skip-update --token "test_token" --run-group 42 --junit-file results/rainforest/junit.xml --save-run-id .rainforest_run_id --custom-url "https://something.com" --description "foo bar" --release "1.0"
      - name: Environment ID and Custom URL command
        id: test_environment_id_custom_url
        uses: ./
        with:
          token: test_token
          run_group_id: 42
          description: foo bar
          environment_id: 117
          custom_url: https://something.com
          release: '1.0'
          dry_run: true
      - name: Environment ID and Custom URL test
        uses: ./.github/actions/test
        with:
          actual: ${{ steps.test_environment_id_custom_url.outputs.command }}
          expected: run --skip-update --token "test_token" --run-group 42 --junit-file results/rainforest/junit.xml --save-run-id .rainforest_run_id --custom-url "https://something.com" --description "foo bar" --release "1.0"
      - name: Missing token command
        id: test_missing_token
        uses: ./
        with:
          dry_run: true
        continue-on-error: true
      - name: Missing token test
        uses: ./.github/actions/test
        with:
          actual: ${{ steps.test_missing_token.outputs.error }}
          expected: Token not set
      - name: Invalid run group command
        id: test_invalid_run_group
        uses: ./
        with:
          token: test_token
          run_group_id: nike
          dry_run: true
        continue-on-error: true
      - name: Invalid run group test
        uses: ./.github/actions/test
        with:
          actual: ${{ steps.test_invalid_run_group.outputs.error }}
          expected: run_group_id not a positive integer (nike)
      - name: Invalid environment ID command
        id: test_invalid_environment_id
        uses: ./
        with:
          token: test_token
          run_group_id: 42
          environment_id: hostile
          dry_run: true
        continue-on-error: true
      - name: Invalid environment ID test
        uses: ./.github/actions/test
        with:
          actual: ${{ steps.test_invalid_environment_id.outputs.error }}
          expected: environment_id not a positive integer (hostile)
      - name: Invalid conflict command
        id: test_invalid_conflict
        uses: ./
        with:
          token: test_token
          run_group_id: 42
          conflict: WWIII
          dry_run: true
        continue-on-error: true
      - name: Invalid conflict test
        uses: ./.github/actions/test
        with:
          actual: ${{ steps.test_invalid_conflict.outputs.error }}
          expected: WWIII not in (cancel cancel-all)
      - name: Invalid crowd command
        id: test_invalid_crowd
        uses: ./
        with:
          token: test_token
          run_group_id: 42
          crowd: hipsters
          dry_run: true
        continue-on-error: true
      - name: Invalid crowd test
        uses: ./.github/actions/test
        with:
          actual: ${{ steps.test_invalid_crowd.outputs.error }}
          expected: hipsters not in (default automation automation_and_crowd on_premise_crowd)
      - name: Invalid parameter generic test
        uses: ./.github/actions/test
        with:
          each: true
          actual: |-
            ${{ steps.test_missing_token.outcome }}
            ${{ steps.test_invalid_run_group.outcome }}
            ${{ steps.test_invalid_environment_id.outcome }}
            ${{ steps.test_invalid_conflict.outcome }}
            ${{ steps.test_invalid_crowd.outcome }}
          expected: failure
      - name: Rerun test setup
        run: |
          echo "343" > .rainforest_run_id
      - name: Rerun command
        id: test_rerun
        uses: ./
        with:
          token: test_token
          run_group_id: 42
          environment_id: 117
          description: foo bar
          conflict: cancel
          crowd: automation
          release: '1.0'
          background: true
          dry_run: true
      - name: Rerun test
        uses: ./.github/actions/test
        with:
          actual: ${{ steps.test_rerun.outputs.command }}
          expected: rerun "343" --skip-update --token "test_token" --junit-file results/rainforest/junit.xml --save-run-id .rainforest_run_id --conflict cancel --release "1.0" --background
