on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Test & Deploy
    steps:
      - uses: actions/checkout@master
      - name: Rainforest
        uses: rainforestapp/rainforest-github-action@master
        env:
          RAINFOREST_API_TOKEN: ${{ secrets.RAINFOREST_API_TOKEN }}